[package]
name = "wyzie-subs"
version = "0.1.0"
edition = "2024"

[features]
utoipa-impl = ["dep:utoipa"]
schemars-impl = ["dep:schemars"]
default = []

[dependencies]
reqwest = { version = "0.12.15", features = ["rustls-tls", "http2", "charset", "json"], default-features = false }
schemars = { version = "1.1.0", optional = true }
serde = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
typed-builder = "0.23.0"
url = { version = "2.5.7", features = ["serde"] }
utoipa = { version = "5.4.0", optional = true }
